[from]
chain = "arbitrum"
datasource = "rpc"
dapp_type = "gmx_v2"
start = "2025-1-8"
end = "2025-1-8"

[from.gmx_v2] # only necessary for ToType==pool/minute, because for raw, tick, price, data in all gmx pool will be downloaded
gm_address = "0x70d95587d40A2caf56bd97485aB3Eec10Bee6336"
virtual_token = "PERP:ETH/USD" # gmx tick for filter VirtualPositionInventoryUpdated

[from.gmx_v2.long_token]
name = "weth"
decimal = 18
address = "0x82af49447d8a07e3bd95bd0d56f35241523fbab1"

[from.gmx_v2.short_token]
name = "usdc"
decimal = 6
address = "0xaf88d065e77c8cc2239327c5edb3a432268e5831"

[from.gmx_v2.index_token]
name = "weth"
decimal = 18
address = "0x82af49447d8a07e3bd95bd0d56f35241523fbab1"

[from.rpc]
end_point = "http://192.168.0.100:8545"
thread = 2

[to]
type = "minute"
save_path = "/data/gmx_v2/arbitrum/"
